components:
  schemas:
    CommandResponse:
      additionalProperties: false
      properties:
        stderr:
          description: Standard error output from the command
          type: string
        stdout:
          description: Standard output from the command
          type: string
      required:
      - stderr
      - stdout
      type: object
    Environment:
      description: |-
        Type of environment to use.
        This is used to determine which languages are installed by default.
      enum:
      - Nodejs
      - Go
      - Bash
      - Rust
      - Python3
      - PHP
      - Java
      - Perl
      - DotNET
      format: env
      type: string
info:
  description: A plugin that allows writting and reading files and running processes in a cloud environment.
  title: E2B Code Interpreter
  version: v1
openapi: 3.0.0
paths:
  /commands:
    post:
      operationId: RunCommand
      parameters:
      - description: Working directory to run the command in
        in: query
        name: workDir
        required: true
        schema:
          type: string
      - description: Environment to run the command in
        in: query
        name: env
        required: false
        schema:
          $ref: '#/components/schemas/Environment'
      requestBody:
        content:
          text/plain; charset=UTF-8:
            schema:
              description: Command to run
              type: string
        description: Command to run
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommandResponse'
          description: JSON containing the standard output and error output of the command
      summary: Run a command in a shell
  /files:
    get:
      operationId: ReadFile
      parameters:
      - description: Environment where to read the file from
        in: query
        name: env
        required: false
        schema:
          $ref: '#/components/schemas/Environment'
      - description: Path to the file to read
        in: query
        name: path
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            text/plain; charset=UTF-8:
              schema:
                type: string
          description: Contents of the file as a string
      summary: Read the contents of a file at the given path
    put:
      operationId: WriteFile
      parameters:
      - description: Environment where to write the file
        in: query
        name: env
        required: false
        schema:
          $ref: '#/components/schemas/Environment'
      - description: Path to the file to write
        in: query
        name: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          text/plain; charset=UTF-8:
            schema:
              description: Content to write to the file
              type: string
        description: Content to write to the file
        required: true
      responses:
        '204':
          description: No content
      summary: Write content to a file at the given path
servers:
- description: Local development
  url: http://localhost:3000/
