components:
  schemas:
    CommandResponse:
      additionalProperties: false
      properties:
        stderr:
          type: string
        stdout:
          type: string
      required:
      - stderr
      - stdout
      type: object
    Environment:
      enum:
      - Nodejs
      - Go
      - Bash
      - Rust
      - Python3
      - PHP
      - Java
      - Perl
      - DotNET
      type: string
info:
  description: A plugin that allows the user to create and manage a TODO list using ChatGPT.
  title: TODO Plugin
  version: v1
openapi: 3.0.0
paths:
  /commands:
    post:
      operationId: RunCommand
      parameters:
      - in: query
        name: workDir
        required: true
        schema:
          type: string
      - in: header
        name: env
        required: false
        schema:
          $ref: '#/components/schemas/Environment'
      requestBody:
        content:
          text/plain; charset=UTF-8:
            schema:
              type: string
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommandResponse'
          description: Ok
  /files:
    get:
      operationId: ReadFile
      parameters:
      - in: header
        name: env
        required: false
        schema:
          $ref: '#/components/schemas/Environment'
      - in: query
        name: path
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            text/plain; charset=UTF-8:
              schema:
                type: string
          description: Ok
    put:
      operationId: WriteFile
      parameters:
      - in: header
        name: env
        required: false
        schema:
          $ref: '#/components/schemas/Environment'
      - in: query
        name: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          text/plain; charset=UTF-8:
            schema:
              type: string
        required: true
      responses:
        '204':
          description: No content
servers:
- description: Local development
  url: http://localhost:3000/
